version: '3.8'

services:
  
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo_data:/data/db

 
  backend:
    image: node:22
    working_dir: /app
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://admin:admin123@mongo:27017/designsight?authSource=admin
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=5001
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npm start"
    depends_on:
      - mongo

  
  frontend:
    image: node:22
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 3000"
    depends_on:
      - backend

volumes:
  mongo_data:
