services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - design-sight-net

  backend:
    build: ./backend
    container_name: backend
    ports:
      - '5001:5001'
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    networks:
      - design-sight-net
    command: npm run dev

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - design-sight-net

volumes:
  mongo-data:

networks:
  design-sight-net:
    driver: bridge